// @generated by tools/gen.py from design/sheets/hooks.json. Do not edit: change the sheet and regenerate.
#![allow(non_snake_case, non_camel_case_types, dead_code, clippy::all)]

use core::ffi::c_void;
use core::sync::atomic::{AtomicPtr, Ordering};

pub struct HookSpec {
    pub id: &'static str,
    pub system: &'static str,
    pub module: &'static str,
    pub fallback_module: &'static str,
    pub function: &'static str,
    pub optional: bool,
    pub detour: *mut c_void,
    pub original: &'static AtomicPtr<c_void>,
}

// ---- fs_createfilew: CreateFileW (kernelbase.dll) -> redirect_paths  [system: save_redirect]
pub type FnFsCreatefilew = unsafe extern "system" fn(*const u16, u32, u32, *const c_void, u32, u32, isize) -> isize;
pub static ORIG_FS_CREATEFILEW: AtomicPtr<c_void> = AtomicPtr::new(core::ptr::null_mut());
pub unsafe extern "system" fn detour_fs_createfilew(lpFileName: *const u16, dwDesiredAccess: u32, dwShareMode: u32, lpSecurityAttributes: *const c_void, dwCreationDisposition: u32, dwFlagsAndAttributes: u32, hTemplateFile: isize) -> isize {
    let orig: FnFsCreatefilew = core::mem::transmute(ORIG_FS_CREATEFILEW.load(Ordering::Relaxed));
    let r0 = crate::guard::redirect_wide(lpFileName, "fs_createfilew");
    let lpFileName = crate::guard::ptr_or(&r0, lpFileName);
    orig(lpFileName, dwDesiredAccess, dwShareMode, lpSecurityAttributes, dwCreationDisposition, dwFlagsAndAttributes, hTemplateFile)
}
const _: FnFsCreatefilew = detour_fs_createfilew;

// ---- fs_createfile2: CreateFile2 (kernelbase.dll) -> redirect_paths  [system: save_redirect]
pub type FnFsCreatefile2 = unsafe extern "system" fn(*const u16, u32, u32, u32, *const c_void) -> isize;
pub static ORIG_FS_CREATEFILE2: AtomicPtr<c_void> = AtomicPtr::new(core::ptr::null_mut());
pub unsafe extern "system" fn detour_fs_createfile2(lpFileName: *const u16, dwDesiredAccess: u32, dwShareMode: u32, dwCreationDisposition: u32, pCreateExParams: *const c_void) -> isize {
    let orig: FnFsCreatefile2 = core::mem::transmute(ORIG_FS_CREATEFILE2.load(Ordering::Relaxed));
    let r0 = crate::guard::redirect_wide(lpFileName, "fs_createfile2");
    let lpFileName = crate::guard::ptr_or(&r0, lpFileName);
    orig(lpFileName, dwDesiredAccess, dwShareMode, dwCreationDisposition, pCreateExParams)
}
const _: FnFsCreatefile2 = detour_fs_createfile2;

// ---- fs_getfileattributesw: GetFileAttributesW (kernelbase.dll) -> redirect_paths  [system: save_redirect]
pub type FnFsGetfileattributesw = unsafe extern "system" fn(*const u16) -> u32;
pub static ORIG_FS_GETFILEATTRIBUTESW: AtomicPtr<c_void> = AtomicPtr::new(core::ptr::null_mut());
pub unsafe extern "system" fn detour_fs_getfileattributesw(lpFileName: *const u16) -> u32 {
    let orig: FnFsGetfileattributesw = core::mem::transmute(ORIG_FS_GETFILEATTRIBUTESW.load(Ordering::Relaxed));
    let r0 = crate::guard::redirect_wide(lpFileName, "fs_getfileattributesw");
    let lpFileName = crate::guard::ptr_or(&r0, lpFileName);
    orig(lpFileName)
}
const _: FnFsGetfileattributesw = detour_fs_getfileattributesw;

// ---- fs_getfileattributesexw: GetFileAttributesExW (kernelbase.dll) -> redirect_paths  [system: save_redirect]
pub type FnFsGetfileattributesexw = unsafe extern "system" fn(*const u16, i32, *mut c_void) -> i32;
pub static ORIG_FS_GETFILEATTRIBUTESEXW: AtomicPtr<c_void> = AtomicPtr::new(core::ptr::null_mut());
pub unsafe extern "system" fn detour_fs_getfileattributesexw(lpFileName: *const u16, fInfoLevelId: i32, lpFileInformation: *mut c_void) -> i32 {
    let orig: FnFsGetfileattributesexw = core::mem::transmute(ORIG_FS_GETFILEATTRIBUTESEXW.load(Ordering::Relaxed));
    let r0 = crate::guard::redirect_wide(lpFileName, "fs_getfileattributesexw");
    let lpFileName = crate::guard::ptr_or(&r0, lpFileName);
    orig(lpFileName, fInfoLevelId, lpFileInformation)
}
const _: FnFsGetfileattributesexw = detour_fs_getfileattributesexw;

// ---- fs_findfirstfilew: FindFirstFileW (kernelbase.dll) -> redirect_paths  [system: save_redirect]
pub type FnFsFindfirstfilew = unsafe extern "system" fn(*const u16, *mut c_void) -> isize;
pub static ORIG_FS_FINDFIRSTFILEW: AtomicPtr<c_void> = AtomicPtr::new(core::ptr::null_mut());
pub unsafe extern "system" fn detour_fs_findfirstfilew(lpFileName: *const u16, lpFindFileData: *mut c_void) -> isize {
    let orig: FnFsFindfirstfilew = core::mem::transmute(ORIG_FS_FINDFIRSTFILEW.load(Ordering::Relaxed));
    let r0 = crate::guard::redirect_wide(lpFileName, "fs_findfirstfilew");
    let lpFileName = crate::guard::ptr_or(&r0, lpFileName);
    orig(lpFileName, lpFindFileData)
}
const _: FnFsFindfirstfilew = detour_fs_findfirstfilew;

// ---- fs_findfirstfileexw: FindFirstFileExW (kernelbase.dll) -> redirect_paths  [system: save_redirect]
pub type FnFsFindfirstfileexw = unsafe extern "system" fn(*const u16, i32, *mut c_void, i32, *const c_void, u32) -> isize;
pub static ORIG_FS_FINDFIRSTFILEEXW: AtomicPtr<c_void> = AtomicPtr::new(core::ptr::null_mut());
pub unsafe extern "system" fn detour_fs_findfirstfileexw(lpFileName: *const u16, fInfoLevelId: i32, lpFindFileData: *mut c_void, fSearchOp: i32, lpSearchFilter: *const c_void, dwAdditionalFlags: u32) -> isize {
    let orig: FnFsFindfirstfileexw = core::mem::transmute(ORIG_FS_FINDFIRSTFILEEXW.load(Ordering::Relaxed));
    let r0 = crate::guard::redirect_wide(lpFileName, "fs_findfirstfileexw");
    let lpFileName = crate::guard::ptr_or(&r0, lpFileName);
    orig(lpFileName, fInfoLevelId, lpFindFileData, fSearchOp, lpSearchFilter, dwAdditionalFlags)
}
const _: FnFsFindfirstfileexw = detour_fs_findfirstfileexw;

// ---- fs_createdirectoryw: CreateDirectoryW (kernelbase.dll) -> redirect_paths  [system: save_redirect]
pub type FnFsCreatedirectoryw = unsafe extern "system" fn(*const u16, *const c_void) -> i32;
pub static ORIG_FS_CREATEDIRECTORYW: AtomicPtr<c_void> = AtomicPtr::new(core::ptr::null_mut());
pub unsafe extern "system" fn detour_fs_createdirectoryw(lpPathName: *const u16, lpSecurityAttributes: *const c_void) -> i32 {
    let orig: FnFsCreatedirectoryw = core::mem::transmute(ORIG_FS_CREATEDIRECTORYW.load(Ordering::Relaxed));
    let r0 = crate::guard::redirect_wide(lpPathName, "fs_createdirectoryw");
    let lpPathName = crate::guard::ptr_or(&r0, lpPathName);
    orig(lpPathName, lpSecurityAttributes)
}
const _: FnFsCreatedirectoryw = detour_fs_createdirectoryw;

// ---- fs_createdirectoryexw: CreateDirectoryExW (kernelbase.dll) -> redirect_paths  [system: save_redirect]
pub type FnFsCreatedirectoryexw = unsafe extern "system" fn(*const u16, *const u16, *const c_void) -> i32;
pub static ORIG_FS_CREATEDIRECTORYEXW: AtomicPtr<c_void> = AtomicPtr::new(core::ptr::null_mut());
pub unsafe extern "system" fn detour_fs_createdirectoryexw(lpTemplateDirectory: *const u16, lpNewDirectory: *const u16, lpSecurityAttributes: *const c_void) -> i32 {
    let orig: FnFsCreatedirectoryexw = core::mem::transmute(ORIG_FS_CREATEDIRECTORYEXW.load(Ordering::Relaxed));
    let r0 = crate::guard::redirect_wide(lpTemplateDirectory, "fs_createdirectoryexw");
    let lpTemplateDirectory = crate::guard::ptr_or(&r0, lpTemplateDirectory);
    let r1 = crate::guard::redirect_wide(lpNewDirectory, "fs_createdirectoryexw");
    let lpNewDirectory = crate::guard::ptr_or(&r1, lpNewDirectory);
    orig(lpTemplateDirectory, lpNewDirectory, lpSecurityAttributes)
}
const _: FnFsCreatedirectoryexw = detour_fs_createdirectoryexw;

// ---- fs_removedirectoryw: RemoveDirectoryW (kernelbase.dll) -> redirect_paths  [system: save_redirect]
pub type FnFsRemovedirectoryw = unsafe extern "system" fn(*const u16) -> i32;
pub static ORIG_FS_REMOVEDIRECTORYW: AtomicPtr<c_void> = AtomicPtr::new(core::ptr::null_mut());
pub unsafe extern "system" fn detour_fs_removedirectoryw(lpPathName: *const u16) -> i32 {
    let orig: FnFsRemovedirectoryw = core::mem::transmute(ORIG_FS_REMOVEDIRECTORYW.load(Ordering::Relaxed));
    let r0 = crate::guard::redirect_wide(lpPathName, "fs_removedirectoryw");
    let lpPathName = crate::guard::ptr_or(&r0, lpPathName);
    orig(lpPathName)
}
const _: FnFsRemovedirectoryw = detour_fs_removedirectoryw;

// ---- fs_deletefilew: DeleteFileW (kernelbase.dll) -> redirect_paths  [system: save_redirect]
pub type FnFsDeletefilew = unsafe extern "system" fn(*const u16) -> i32;
pub static ORIG_FS_DELETEFILEW: AtomicPtr<c_void> = AtomicPtr::new(core::ptr::null_mut());
pub unsafe extern "system" fn detour_fs_deletefilew(lpFileName: *const u16) -> i32 {
    let orig: FnFsDeletefilew = core::mem::transmute(ORIG_FS_DELETEFILEW.load(Ordering::Relaxed));
    let r0 = crate::guard::redirect_wide(lpFileName, "fs_deletefilew");
    let lpFileName = crate::guard::ptr_or(&r0, lpFileName);
    orig(lpFileName)
}
const _: FnFsDeletefilew = detour_fs_deletefilew;

// ---- fs_setfileattributesw: SetFileAttributesW (kernelbase.dll) -> redirect_paths  [system: save_redirect]
pub type FnFsSetfileattributesw = unsafe extern "system" fn(*const u16, u32) -> i32;
pub static ORIG_FS_SETFILEATTRIBUTESW: AtomicPtr<c_void> = AtomicPtr::new(core::ptr::null_mut());
pub unsafe extern "system" fn detour_fs_setfileattributesw(lpFileName: *const u16, dwFileAttributes: u32) -> i32 {
    let orig: FnFsSetfileattributesw = core::mem::transmute(ORIG_FS_SETFILEATTRIBUTESW.load(Ordering::Relaxed));
    let r0 = crate::guard::redirect_wide(lpFileName, "fs_setfileattributesw");
    let lpFileName = crate::guard::ptr_or(&r0, lpFileName);
    orig(lpFileName, dwFileAttributes)
}
const _: FnFsSetfileattributesw = detour_fs_setfileattributesw;

// ---- fs_movefilew: MoveFileW (kernelbase.dll) -> redirect_paths  [system: save_redirect]
pub type FnFsMovefilew = unsafe extern "system" fn(*const u16, *const u16) -> i32;
pub static ORIG_FS_MOVEFILEW: AtomicPtr<c_void> = AtomicPtr::new(core::ptr::null_mut());
pub unsafe extern "system" fn detour_fs_movefilew(lpExistingFileName: *const u16, lpNewFileName: *const u16) -> i32 {
    let orig: FnFsMovefilew = core::mem::transmute(ORIG_FS_MOVEFILEW.load(Ordering::Relaxed));
    let r0 = crate::guard::redirect_wide(lpExistingFileName, "fs_movefilew");
    let lpExistingFileName = crate::guard::ptr_or(&r0, lpExistingFileName);
    let r1 = crate::guard::redirect_wide(lpNewFileName, "fs_movefilew");
    let lpNewFileName = crate::guard::ptr_or(&r1, lpNewFileName);
    orig(lpExistingFileName, lpNewFileName)
}
const _: FnFsMovefilew = detour_fs_movefilew;

// ---- fs_movefileexw: MoveFileExW (kernelbase.dll) -> redirect_paths  [system: save_redirect]
pub type FnFsMovefileexw = unsafe extern "system" fn(*const u16, *const u16, u32) -> i32;
pub static ORIG_FS_MOVEFILEEXW: AtomicPtr<c_void> = AtomicPtr::new(core::ptr::null_mut());
pub unsafe extern "system" fn detour_fs_movefileexw(lpExistingFileName: *const u16, lpNewFileName: *const u16, dwFlags: u32) -> i32 {
    let orig: FnFsMovefileexw = core::mem::transmute(ORIG_FS_MOVEFILEEXW.load(Ordering::Relaxed));
    let r0 = crate::guard::redirect_wide(lpExistingFileName, "fs_movefileexw");
    let lpExistingFileName = crate::guard::ptr_or(&r0, lpExistingFileName);
    let r1 = crate::guard::redirect_wide(lpNewFileName, "fs_movefileexw");
    let lpNewFileName = crate::guard::ptr_or(&r1, lpNewFileName);
    orig(lpExistingFileName, lpNewFileName, dwFlags)
}
const _: FnFsMovefileexw = detour_fs_movefileexw;

// ---- fs_movefilewithprogressw: MoveFileWithProgressW (kernelbase.dll) -> redirect_paths  [system: save_redirect]
pub type FnFsMovefilewithprogressw = unsafe extern "system" fn(*const u16, *const u16, *const c_void, *const c_void, u32) -> i32;
pub static ORIG_FS_MOVEFILEWITHPROGRESSW: AtomicPtr<c_void> = AtomicPtr::new(core::ptr::null_mut());
pub unsafe extern "system" fn detour_fs_movefilewithprogressw(lpExistingFileName: *const u16, lpNewFileName: *const u16, lpProgressRoutine: *const c_void, lpData: *const c_void, dwFlags: u32) -> i32 {
    let orig: FnFsMovefilewithprogressw = core::mem::transmute(ORIG_FS_MOVEFILEWITHPROGRESSW.load(Ordering::Relaxed));
    let r0 = crate::guard::redirect_wide(lpExistingFileName, "fs_movefilewithprogressw");
    let lpExistingFileName = crate::guard::ptr_or(&r0, lpExistingFileName);
    let r1 = crate::guard::redirect_wide(lpNewFileName, "fs_movefilewithprogressw");
    let lpNewFileName = crate::guard::ptr_or(&r1, lpNewFileName);
    orig(lpExistingFileName, lpNewFileName, lpProgressRoutine, lpData, dwFlags)
}
const _: FnFsMovefilewithprogressw = detour_fs_movefilewithprogressw;

// ---- fs_copyfilew: CopyFileW (kernelbase.dll) -> redirect_paths  [system: save_redirect]
pub type FnFsCopyfilew = unsafe extern "system" fn(*const u16, *const u16, i32) -> i32;
pub static ORIG_FS_COPYFILEW: AtomicPtr<c_void> = AtomicPtr::new(core::ptr::null_mut());
pub unsafe extern "system" fn detour_fs_copyfilew(lpExistingFileName: *const u16, lpNewFileName: *const u16, bFailIfExists: i32) -> i32 {
    let orig: FnFsCopyfilew = core::mem::transmute(ORIG_FS_COPYFILEW.load(Ordering::Relaxed));
    let r0 = crate::guard::redirect_wide(lpExistingFileName, "fs_copyfilew");
    let lpExistingFileName = crate::guard::ptr_or(&r0, lpExistingFileName);
    let r1 = crate::guard::redirect_wide(lpNewFileName, "fs_copyfilew");
    let lpNewFileName = crate::guard::ptr_or(&r1, lpNewFileName);
    orig(lpExistingFileName, lpNewFileName, bFailIfExists)
}
const _: FnFsCopyfilew = detour_fs_copyfilew;

// ---- fs_copyfileexw: CopyFileExW (kernelbase.dll) -> redirect_paths  [system: save_redirect]
pub type FnFsCopyfileexw = unsafe extern "system" fn(*const u16, *const u16, *const c_void, *const c_void, *mut i32, u32) -> i32;
pub static ORIG_FS_COPYFILEEXW: AtomicPtr<c_void> = AtomicPtr::new(core::ptr::null_mut());
pub unsafe extern "system" fn detour_fs_copyfileexw(lpExistingFileName: *const u16, lpNewFileName: *const u16, lpProgressRoutine: *const c_void, lpData: *const c_void, pbCancel: *mut i32, dwCopyFlags: u32) -> i32 {
    let orig: FnFsCopyfileexw = core::mem::transmute(ORIG_FS_COPYFILEEXW.load(Ordering::Relaxed));
    let r0 = crate::guard::redirect_wide(lpExistingFileName, "fs_copyfileexw");
    let lpExistingFileName = crate::guard::ptr_or(&r0, lpExistingFileName);
    let r1 = crate::guard::redirect_wide(lpNewFileName, "fs_copyfileexw");
    let lpNewFileName = crate::guard::ptr_or(&r1, lpNewFileName);
    orig(lpExistingFileName, lpNewFileName, lpProgressRoutine, lpData, pbCancel, dwCopyFlags)
}
const _: FnFsCopyfileexw = detour_fs_copyfileexw;

// ---- fs_replacefilew: ReplaceFileW (kernelbase.dll) -> redirect_paths  [system: save_redirect]
pub type FnFsReplacefilew = unsafe extern "system" fn(*const u16, *const u16, *const u16, u32, *mut c_void, *mut c_void) -> i32;
pub static ORIG_FS_REPLACEFILEW: AtomicPtr<c_void> = AtomicPtr::new(core::ptr::null_mut());
pub unsafe extern "system" fn detour_fs_replacefilew(lpReplacedFileName: *const u16, lpReplacementFileName: *const u16, lpBackupFileName: *const u16, dwReplaceFlags: u32, lpExclude: *mut c_void, lpReserved: *mut c_void) -> i32 {
    let orig: FnFsReplacefilew = core::mem::transmute(ORIG_FS_REPLACEFILEW.load(Ordering::Relaxed));
    let r0 = crate::guard::redirect_wide(lpReplacedFileName, "fs_replacefilew");
    let lpReplacedFileName = crate::guard::ptr_or(&r0, lpReplacedFileName);
    let r1 = crate::guard::redirect_wide(lpReplacementFileName, "fs_replacefilew");
    let lpReplacementFileName = crate::guard::ptr_or(&r1, lpReplacementFileName);
    let r2 = crate::guard::redirect_wide(lpBackupFileName, "fs_replacefilew");
    let lpBackupFileName = crate::guard::ptr_or(&r2, lpBackupFileName);
    orig(lpReplacedFileName, lpReplacementFileName, lpBackupFileName, dwReplaceFlags, lpExclude, lpReserved)
}
const _: FnFsReplacefilew = detour_fs_replacefilew;

// ---- net_connect: connect (ws2_32.dll) -> deny_addr  [system: offline_guard]
pub type FnNetConnect = unsafe extern "system" fn(usize, *const c_void, i32) -> i32;
pub static ORIG_NET_CONNECT: AtomicPtr<c_void> = AtomicPtr::new(core::ptr::null_mut());
pub unsafe extern "system" fn detour_net_connect(s: usize, name: *const c_void, namelen: i32) -> i32 {
    let orig: FnNetConnect = core::mem::transmute(ORIG_NET_CONNECT.load(Ordering::Relaxed));
    if crate::guard::addr_denied("net_connect", name as *const u8) {
        crate::guard::set_last_error_wsa(10061);
        return -1;
    }
    orig(s, name, namelen)
}
const _: FnNetConnect = detour_net_connect;

// ---- net_wsaconnect: WSAConnect (ws2_32.dll) -> deny_addr  [system: offline_guard]
pub type FnNetWsaconnect = unsafe extern "system" fn(usize, *const c_void, i32, *const c_void, *mut c_void, *const c_void, *const c_void) -> i32;
pub static ORIG_NET_WSACONNECT: AtomicPtr<c_void> = AtomicPtr::new(core::ptr::null_mut());
pub unsafe extern "system" fn detour_net_wsaconnect(s: usize, name: *const c_void, namelen: i32, lpCallerData: *const c_void, lpCalleeData: *mut c_void, lpSQOS: *const c_void, lpGQOS: *const c_void) -> i32 {
    let orig: FnNetWsaconnect = core::mem::transmute(ORIG_NET_WSACONNECT.load(Ordering::Relaxed));
    if crate::guard::addr_denied("net_wsaconnect", name as *const u8) {
        crate::guard::set_last_error_wsa(10061);
        return -1;
    }
    orig(s, name, namelen, lpCallerData, lpCalleeData, lpSQOS, lpGQOS)
}
const _: FnNetWsaconnect = detour_net_wsaconnect;

// ---- net_sendto: sendto (ws2_32.dll) -> deny_addr  [system: offline_guard]
pub type FnNetSendto = unsafe extern "system" fn(usize, *const u8, i32, i32, *const c_void, i32) -> i32;
pub static ORIG_NET_SENDTO: AtomicPtr<c_void> = AtomicPtr::new(core::ptr::null_mut());
pub unsafe extern "system" fn detour_net_sendto(s: usize, buf: *const u8, len: i32, flags: i32, to: *const c_void, tolen: i32) -> i32 {
    let orig: FnNetSendto = core::mem::transmute(ORIG_NET_SENDTO.load(Ordering::Relaxed));
    if crate::guard::addr_denied("net_sendto", to as *const u8) {
        crate::guard::set_last_error_wsa(10051);
        return -1;
    }
    orig(s, buf, len, flags, to, tolen)
}
const _: FnNetSendto = detour_net_sendto;

// ---- net_wsasendto: WSASendTo (ws2_32.dll) -> deny_addr  [system: offline_guard]
pub type FnNetWsasendto = unsafe extern "system" fn(usize, *mut c_void, u32, *mut u32, u32, *const c_void, i32, *mut c_void, *mut c_void) -> i32;
pub static ORIG_NET_WSASENDTO: AtomicPtr<c_void> = AtomicPtr::new(core::ptr::null_mut());
pub unsafe extern "system" fn detour_net_wsasendto(s: usize, lpBuffers: *mut c_void, dwBufferCount: u32, lpNumberOfBytesSent: *mut u32, dwFlags: u32, lpTo: *const c_void, iTolen: i32, lpOverlapped: *mut c_void, lpCompletionRoutine: *mut c_void) -> i32 {
    let orig: FnNetWsasendto = core::mem::transmute(ORIG_NET_WSASENDTO.load(Ordering::Relaxed));
    if crate::guard::addr_denied("net_wsasendto", lpTo as *const u8) {
        crate::guard::set_last_error_wsa(10051);
        return -1;
    }
    orig(s, lpBuffers, dwBufferCount, lpNumberOfBytesSent, dwFlags, lpTo, iTolen, lpOverlapped, lpCompletionRoutine)
}
const _: FnNetWsasendto = detour_net_wsasendto;

// ---- net_wsaioctl: WSAIoctl (ws2_32.dll) -> custom  [system: offline_guard]
pub type FnNetWsaioctl = unsafe extern "system" fn(usize, u32, *mut c_void, u32, *mut c_void, u32, *mut u32, *mut c_void, *mut c_void) -> i32;
pub static ORIG_NET_WSAIOCTL: AtomicPtr<c_void> = AtomicPtr::new(core::ptr::null_mut());
pub use crate::custom::wsaioctl_guard as detour_net_wsaioctl;
const _: FnNetWsaioctl = detour_net_wsaioctl;

// ---- net_getaddrinfo: getaddrinfo (ws2_32.dll) -> deny_name  [system: offline_guard]
pub type FnNetGetaddrinfo = unsafe extern "system" fn(*const u8, *const u8, *const c_void, *mut *mut c_void) -> i32;
pub static ORIG_NET_GETADDRINFO: AtomicPtr<c_void> = AtomicPtr::new(core::ptr::null_mut());
pub unsafe extern "system" fn detour_net_getaddrinfo(pNodeName: *const u8, pServiceName: *const u8, pHints: *const c_void, ppResult: *mut *mut c_void) -> i32 {
    let orig: FnNetGetaddrinfo = core::mem::transmute(ORIG_NET_GETADDRINFO.load(Ordering::Relaxed));
    if crate::guard::name_denied_ansi("net_getaddrinfo", pNodeName) {
        crate::guard::set_last_error_wsa(11001);
        return 11001;
    }
    orig(pNodeName, pServiceName, pHints, ppResult)
}
const _: FnNetGetaddrinfo = detour_net_getaddrinfo;

// ---- net_getaddrinfow: GetAddrInfoW (ws2_32.dll) -> deny_name  [system: offline_guard]
pub type FnNetGetaddrinfow = unsafe extern "system" fn(*const u16, *const u16, *const c_void, *mut *mut c_void) -> i32;
pub static ORIG_NET_GETADDRINFOW: AtomicPtr<c_void> = AtomicPtr::new(core::ptr::null_mut());
pub unsafe extern "system" fn detour_net_getaddrinfow(pNodeName: *const u16, pServiceName: *const u16, pHints: *const c_void, ppResult: *mut *mut c_void) -> i32 {
    let orig: FnNetGetaddrinfow = core::mem::transmute(ORIG_NET_GETADDRINFOW.load(Ordering::Relaxed));
    if crate::guard::name_denied_utf16("net_getaddrinfow", pNodeName) {
        crate::guard::set_last_error_wsa(11001);
        return 11001;
    }
    orig(pNodeName, pServiceName, pHints, ppResult)
}
const _: FnNetGetaddrinfow = detour_net_getaddrinfow;

// ---- net_getaddrinfoexw: GetAddrInfoExW (ws2_32.dll) -> deny_name  [system: offline_guard]
pub type FnNetGetaddrinfoexw = unsafe extern "system" fn(*const u16, *const u16, u32, *mut c_void, *const c_void, *mut *mut c_void, *mut c_void, *mut c_void, *mut c_void, *mut isize) -> i32;
pub static ORIG_NET_GETADDRINFOEXW: AtomicPtr<c_void> = AtomicPtr::new(core::ptr::null_mut());
pub unsafe extern "system" fn detour_net_getaddrinfoexw(pName: *const u16, pServiceName: *const u16, dwNameSpace: u32, lpNspId: *mut c_void, hints: *const c_void, ppResult: *mut *mut c_void, timeout: *mut c_void, lpOverlapped: *mut c_void, lpCompletionRoutine: *mut c_void, lpHandle: *mut isize) -> i32 {
    let orig: FnNetGetaddrinfoexw = core::mem::transmute(ORIG_NET_GETADDRINFOEXW.load(Ordering::Relaxed));
    if crate::guard::name_denied_utf16("net_getaddrinfoexw", pName) {
        crate::guard::set_last_error_wsa(11001);
        return 11001;
    }
    orig(pName, pServiceName, dwNameSpace, lpNspId, hints, ppResult, timeout, lpOverlapped, lpCompletionRoutine, lpHandle)
}
const _: FnNetGetaddrinfoexw = detour_net_getaddrinfoexw;

// ---- net_gethostbyname: gethostbyname (ws2_32.dll) -> deny_name  [system: offline_guard]
pub type FnNetGethostbyname = unsafe extern "system" fn(*const u8) -> *mut c_void;
pub static ORIG_NET_GETHOSTBYNAME: AtomicPtr<c_void> = AtomicPtr::new(core::ptr::null_mut());
pub unsafe extern "system" fn detour_net_gethostbyname(name: *const u8) -> *mut c_void {
    let orig: FnNetGethostbyname = core::mem::transmute(ORIG_NET_GETHOSTBYNAME.load(Ordering::Relaxed));
    if crate::guard::name_denied_ansi("net_gethostbyname", name) {
        crate::guard::set_last_error_wsa(11001);
        return core::ptr::null_mut();
    }
    orig(name)
}
const _: FnNetGethostbyname = detour_net_gethostbyname;

// ---- net_wsaconnectbynamew: WSAConnectByNameW (ws2_32.dll) -> deny_name  [system: offline_guard]
pub type FnNetWsaconnectbynamew = unsafe extern "system" fn(usize, *const u16, *const u16, *mut u32, *mut c_void, *mut u32, *mut c_void, *const c_void, *mut c_void) -> i32;
pub static ORIG_NET_WSACONNECTBYNAMEW: AtomicPtr<c_void> = AtomicPtr::new(core::ptr::null_mut());
pub unsafe extern "system" fn detour_net_wsaconnectbynamew(s: usize, nodename: *const u16, servicename: *const u16, lpLocalAddressLength: *mut u32, lpLocalAddress: *mut c_void, lpRemoteAddressLength: *mut u32, lpRemoteAddress: *mut c_void, timeout: *const c_void, reserved: *mut c_void) -> i32 {
    let orig: FnNetWsaconnectbynamew = core::mem::transmute(ORIG_NET_WSACONNECTBYNAMEW.load(Ordering::Relaxed));
    if crate::guard::name_denied_utf16("net_wsaconnectbynamew", nodename) {
        crate::guard::set_last_error_wsa(10061);
        return 0;
    }
    orig(s, nodename, servicename, lpLocalAddressLength, lpLocalAddress, lpRemoteAddressLength, lpRemoteAddress, timeout, reserved)
}
const _: FnNetWsaconnectbynamew = detour_net_wsaconnectbynamew;

// ---- http_winhttpconnect: WinHttpConnect (winhttp.dll) -> deny_name  [system: offline_guard]
pub type FnHttpWinhttpconnect = unsafe extern "system" fn(isize, *const u16, u16, u32) -> isize;
pub static ORIG_HTTP_WINHTTPCONNECT: AtomicPtr<c_void> = AtomicPtr::new(core::ptr::null_mut());
pub unsafe extern "system" fn detour_http_winhttpconnect(hSession: isize, pswzServerName: *const u16, nServerPort: u16, dwReserved: u32) -> isize {
    let orig: FnHttpWinhttpconnect = core::mem::transmute(ORIG_HTTP_WINHTTPCONNECT.load(Ordering::Relaxed));
    if crate::guard::name_denied_utf16("http_winhttpconnect", pswzServerName) {
        crate::guard::set_last_error_win32(12029);
        return 0;
    }
    orig(hSession, pswzServerName, nServerPort, dwReserved)
}
const _: FnHttpWinhttpconnect = detour_http_winhttpconnect;

// ---- http_internetconnectw: InternetConnectW (wininet.dll) -> deny_name  [system: offline_guard]
pub type FnHttpInternetconnectw = unsafe extern "system" fn(isize, *const u16, u16, *const u16, *const u16, u32, u32, usize) -> isize;
pub static ORIG_HTTP_INTERNETCONNECTW: AtomicPtr<c_void> = AtomicPtr::new(core::ptr::null_mut());
pub unsafe extern "system" fn detour_http_internetconnectw(hInternet: isize, lpszServerName: *const u16, nServerPort: u16, lpszUserName: *const u16, lpszPassword: *const u16, dwService: u32, dwFlags: u32, dwContext: usize) -> isize {
    let orig: FnHttpInternetconnectw = core::mem::transmute(ORIG_HTTP_INTERNETCONNECTW.load(Ordering::Relaxed));
    if crate::guard::name_denied_utf16("http_internetconnectw", lpszServerName) {
        crate::guard::set_last_error_win32(12029);
        return 0;
    }
    orig(hInternet, lpszServerName, nServerPort, lpszUserName, lpszPassword, dwService, dwFlags, dwContext)
}
const _: FnHttpInternetconnectw = detour_http_internetconnectw;

// ---- http_internetconnecta: InternetConnectA (wininet.dll) -> deny_name  [system: offline_guard]
pub type FnHttpInternetconnecta = unsafe extern "system" fn(isize, *const u8, u16, *const u8, *const u8, u32, u32, usize) -> isize;
pub static ORIG_HTTP_INTERNETCONNECTA: AtomicPtr<c_void> = AtomicPtr::new(core::ptr::null_mut());
pub unsafe extern "system" fn detour_http_internetconnecta(hInternet: isize, lpszServerName: *const u8, nServerPort: u16, lpszUserName: *const u8, lpszPassword: *const u8, dwService: u32, dwFlags: u32, dwContext: usize) -> isize {
    let orig: FnHttpInternetconnecta = core::mem::transmute(ORIG_HTTP_INTERNETCONNECTA.load(Ordering::Relaxed));
    if crate::guard::name_denied_ansi("http_internetconnecta", lpszServerName) {
        crate::guard::set_last_error_win32(12029);
        return 0;
    }
    orig(hInternet, lpszServerName, nServerPort, lpszUserName, lpszPassword, dwService, dwFlags, dwContext)
}
const _: FnHttpInternetconnecta = detour_http_internetconnecta;

pub fn hook_specs() -> Vec<HookSpec> {
    vec![
        HookSpec { id: "fs_createfilew", system: "save_redirect", module: "kernelbase.dll", fallback_module: "kernel32.dll", function: "CreateFileW", optional: false, detour: detour_fs_createfilew as *const () as usize as *mut c_void, original: &ORIG_FS_CREATEFILEW },
        HookSpec { id: "fs_createfile2", system: "save_redirect", module: "kernelbase.dll", fallback_module: "kernel32.dll", function: "CreateFile2", optional: true, detour: detour_fs_createfile2 as *const () as usize as *mut c_void, original: &ORIG_FS_CREATEFILE2 },
        HookSpec { id: "fs_getfileattributesw", system: "save_redirect", module: "kernelbase.dll", fallback_module: "kernel32.dll", function: "GetFileAttributesW", optional: false, detour: detour_fs_getfileattributesw as *const () as usize as *mut c_void, original: &ORIG_FS_GETFILEATTRIBUTESW },
        HookSpec { id: "fs_getfileattributesexw", system: "save_redirect", module: "kernelbase.dll", fallback_module: "kernel32.dll", function: "GetFileAttributesExW", optional: false, detour: detour_fs_getfileattributesexw as *const () as usize as *mut c_void, original: &ORIG_FS_GETFILEATTRIBUTESEXW },
        HookSpec { id: "fs_findfirstfilew", system: "save_redirect", module: "kernelbase.dll", fallback_module: "kernel32.dll", function: "FindFirstFileW", optional: false, detour: detour_fs_findfirstfilew as *const () as usize as *mut c_void, original: &ORIG_FS_FINDFIRSTFILEW },
        HookSpec { id: "fs_findfirstfileexw", system: "save_redirect", module: "kernelbase.dll", fallback_module: "kernel32.dll", function: "FindFirstFileExW", optional: false, detour: detour_fs_findfirstfileexw as *const () as usize as *mut c_void, original: &ORIG_FS_FINDFIRSTFILEEXW },
        HookSpec { id: "fs_createdirectoryw", system: "save_redirect", module: "kernelbase.dll", fallback_module: "kernel32.dll", function: "CreateDirectoryW", optional: false, detour: detour_fs_createdirectoryw as *const () as usize as *mut c_void, original: &ORIG_FS_CREATEDIRECTORYW },
        HookSpec { id: "fs_createdirectoryexw", system: "save_redirect", module: "kernelbase.dll", fallback_module: "kernel32.dll", function: "CreateDirectoryExW", optional: true, detour: detour_fs_createdirectoryexw as *const () as usize as *mut c_void, original: &ORIG_FS_CREATEDIRECTORYEXW },
        HookSpec { id: "fs_removedirectoryw", system: "save_redirect", module: "kernelbase.dll", fallback_module: "kernel32.dll", function: "RemoveDirectoryW", optional: false, detour: detour_fs_removedirectoryw as *const () as usize as *mut c_void, original: &ORIG_FS_REMOVEDIRECTORYW },
        HookSpec { id: "fs_deletefilew", system: "save_redirect", module: "kernelbase.dll", fallback_module: "kernel32.dll", function: "DeleteFileW", optional: false, detour: detour_fs_deletefilew as *const () as usize as *mut c_void, original: &ORIG_FS_DELETEFILEW },
        HookSpec { id: "fs_setfileattributesw", system: "save_redirect", module: "kernelbase.dll", fallback_module: "kernel32.dll", function: "SetFileAttributesW", optional: false, detour: detour_fs_setfileattributesw as *const () as usize as *mut c_void, original: &ORIG_FS_SETFILEATTRIBUTESW },
        HookSpec { id: "fs_movefilew", system: "save_redirect", module: "kernelbase.dll", fallback_module: "kernel32.dll", function: "MoveFileW", optional: false, detour: detour_fs_movefilew as *const () as usize as *mut c_void, original: &ORIG_FS_MOVEFILEW },
        HookSpec { id: "fs_movefileexw", system: "save_redirect", module: "kernelbase.dll", fallback_module: "kernel32.dll", function: "MoveFileExW", optional: false, detour: detour_fs_movefileexw as *const () as usize as *mut c_void, original: &ORIG_FS_MOVEFILEEXW },
        HookSpec { id: "fs_movefilewithprogressw", system: "save_redirect", module: "kernelbase.dll", fallback_module: "kernel32.dll", function: "MoveFileWithProgressW", optional: false, detour: detour_fs_movefilewithprogressw as *const () as usize as *mut c_void, original: &ORIG_FS_MOVEFILEWITHPROGRESSW },
        HookSpec { id: "fs_copyfilew", system: "save_redirect", module: "kernelbase.dll", fallback_module: "kernel32.dll", function: "CopyFileW", optional: false, detour: detour_fs_copyfilew as *const () as usize as *mut c_void, original: &ORIG_FS_COPYFILEW },
        HookSpec { id: "fs_copyfileexw", system: "save_redirect", module: "kernelbase.dll", fallback_module: "kernel32.dll", function: "CopyFileExW", optional: false, detour: detour_fs_copyfileexw as *const () as usize as *mut c_void, original: &ORIG_FS_COPYFILEEXW },
        HookSpec { id: "fs_replacefilew", system: "save_redirect", module: "kernelbase.dll", fallback_module: "kernel32.dll", function: "ReplaceFileW", optional: false, detour: detour_fs_replacefilew as *const () as usize as *mut c_void, original: &ORIG_FS_REPLACEFILEW },
        HookSpec { id: "net_connect", system: "offline_guard", module: "ws2_32.dll", fallback_module: "", function: "connect", optional: false, detour: detour_net_connect as *const () as usize as *mut c_void, original: &ORIG_NET_CONNECT },
        HookSpec { id: "net_wsaconnect", system: "offline_guard", module: "ws2_32.dll", fallback_module: "", function: "WSAConnect", optional: false, detour: detour_net_wsaconnect as *const () as usize as *mut c_void, original: &ORIG_NET_WSACONNECT },
        HookSpec { id: "net_sendto", system: "offline_guard", module: "ws2_32.dll", fallback_module: "", function: "sendto", optional: false, detour: detour_net_sendto as *const () as usize as *mut c_void, original: &ORIG_NET_SENDTO },
        HookSpec { id: "net_wsasendto", system: "offline_guard", module: "ws2_32.dll", fallback_module: "", function: "WSASendTo", optional: false, detour: detour_net_wsasendto as *const () as usize as *mut c_void, original: &ORIG_NET_WSASENDTO },
        HookSpec { id: "net_wsaioctl", system: "offline_guard", module: "ws2_32.dll", fallback_module: "", function: "WSAIoctl", optional: false, detour: detour_net_wsaioctl as *const () as usize as *mut c_void, original: &ORIG_NET_WSAIOCTL },
        HookSpec { id: "net_getaddrinfo", system: "offline_guard", module: "ws2_32.dll", fallback_module: "", function: "getaddrinfo", optional: false, detour: detour_net_getaddrinfo as *const () as usize as *mut c_void, original: &ORIG_NET_GETADDRINFO },
        HookSpec { id: "net_getaddrinfow", system: "offline_guard", module: "ws2_32.dll", fallback_module: "", function: "GetAddrInfoW", optional: false, detour: detour_net_getaddrinfow as *const () as usize as *mut c_void, original: &ORIG_NET_GETADDRINFOW },
        HookSpec { id: "net_getaddrinfoexw", system: "offline_guard", module: "ws2_32.dll", fallback_module: "", function: "GetAddrInfoExW", optional: true, detour: detour_net_getaddrinfoexw as *const () as usize as *mut c_void, original: &ORIG_NET_GETADDRINFOEXW },
        HookSpec { id: "net_gethostbyname", system: "offline_guard", module: "ws2_32.dll", fallback_module: "", function: "gethostbyname", optional: false, detour: detour_net_gethostbyname as *const () as usize as *mut c_void, original: &ORIG_NET_GETHOSTBYNAME },
        HookSpec { id: "net_wsaconnectbynamew", system: "offline_guard", module: "ws2_32.dll", fallback_module: "", function: "WSAConnectByNameW", optional: true, detour: detour_net_wsaconnectbynamew as *const () as usize as *mut c_void, original: &ORIG_NET_WSACONNECTBYNAMEW },
        HookSpec { id: "http_winhttpconnect", system: "offline_guard", module: "winhttp.dll", fallback_module: "", function: "WinHttpConnect", optional: true, detour: detour_http_winhttpconnect as *const () as usize as *mut c_void, original: &ORIG_HTTP_WINHTTPCONNECT },
        HookSpec { id: "http_internetconnectw", system: "offline_guard", module: "wininet.dll", fallback_module: "", function: "InternetConnectW", optional: true, detour: detour_http_internetconnectw as *const () as usize as *mut c_void, original: &ORIG_HTTP_INTERNETCONNECTW },
        HookSpec { id: "http_internetconnecta", system: "offline_guard", module: "wininet.dll", fallback_module: "", function: "InternetConnectA", optional: true, detour: detour_http_internetconnecta as *const () as usize as *mut c_void, original: &ORIG_HTTP_INTERNETCONNECTA },
    ]
}
