#!/usr/bin/env python3
"""Generate Rust from the design sheets. Each row becomes one piece of code built from that row's columns.

    python3 tools/gen.py           # (re)write generated files
    python3 tools/gen.py --check   # exit 1 if a generated file is stale (use in CI / before building)

Generated files (never edit by hand; change the sheet, then regenerate):
    crates/common/src/generated/files.rs   <- design/sheets/files.json   (one FileRule per row)
    crates/hook/src/generated.rs           <- design/sheets/hooks.json   (one detour + one install entry per row)
"""
import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SHEETS = ROOT / "design" / "sheets"
HEADER = "// @generated by tools/gen.py from design/sheets/{sheet}.json. Do not edit: change the sheet and regenerate.\n"


def load(name):
    return json.loads((SHEETS / f"{name}.json").read_text(encoding="utf-8"))


def rs(s):
    """Rust string literal."""
    out = ['"']
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


def pascal(s):
    return "".join(p.capitalize() for p in s.split("_"))


def rows_up_to(sheet, ms):
    return [r for r in sheet["rows"] if r.get("milestone", 0) <= ms]


# --------------------------------------------------------------------------------------------- files

def gen_files(ms):
    sheet = load("files")
    rows = rows_up_to(sheet, ms)
    o = [HEADER.format(sheet="files"), "#![allow(dead_code)]\n", "use crate::paths::{Access, FileRule};\n\n"]
    for r in rows:
        o.append(f"pub const {r['id'].upper()}: &str = {rs(r['id'])};\n")
    o.append("\npub static FILES: &[FileRule] = &[\n")
    acc = {"read": "Access::Read", "write": "Access::Write", "readwrite": "Access::ReadWrite"}
    for r in rows:
        o.append(
            "    FileRule {\n"
            f"        id: {rs(r['id'])},\n"
            f"        path: {rs(r['path'])},\n"
            f"        purpose: {rs(r['purpose'])},\n"
            f"        access: {acc[r['access']]},\n"
            f"        system: {rs(r['system'])},\n"
            f"        guarded: {str(r['guarded']).lower()},\n"
            f"        milestone: {r['milestone']},\n"
            "    },\n"
        )
    o.append("];\n")
    return "".join(o)


# --------------------------------------------------------------------------------------------- hooks

def gen_hooks(ms):
    sheet = load("hooks")
    rows = rows_up_to(sheet, ms)
    o = [
        HEADER.format(sheet="hooks"),
        "#![allow(non_snake_case, non_camel_case_types, dead_code, clippy::all)]\n\n",
        "use core::ffi::c_void;\n",
        "use core::sync::atomic::{AtomicPtr, Ordering};\n\n",
        "pub struct HookSpec {\n"
        "    pub id: &'static str,\n"
        "    pub system: &'static str,\n"
        "    pub module: &'static str,\n"
        "    pub fallback_module: &'static str,\n"
        "    pub function: &'static str,\n"
        "    pub optional: bool,\n"
        "    pub detour: *mut c_void,\n"
        "    pub original: &'static AtomicPtr<c_void>,\n"
        "}\n\n",
    ]
    specs = []
    for r in rows:
        hid, up, pas = r["id"], r["id"].upper(), pascal(r["id"])
        args = [a.split(":", 1) for a in r["args"]]
        params = ", ".join(f"{n}: {t}" for n, t in args)
        names = ", ".join(n for n, _ in args)
        types = ", ".join(t for _, t in args)
        ret = r["ret"]
        fn_ty = f"Fn{pas}"
        act = r["action"]
        o.append(f"// ---- {hid}: {r['function']} ({r['module']}) -> {r['action']}  [system: {r['system']}]\n")
        o.append(f"pub type {fn_ty} = unsafe extern \"system\" fn({types}) -> {ret};\n")
        o.append(f"pub static ORIG_{up}: AtomicPtr<c_void> = AtomicPtr::new(core::ptr::null_mut());\n")
        if act == "custom":
            o.append(f"pub use crate::custom::{r['custom_fn']} as detour_{hid};\n")
        else:
            body = []
            if act == "redirect_paths":
                for i in r["target_args"]:
                    n = args[i][0]
                    body.append(f"    let r{i} = crate::guard::redirect_wide({n}, {rs(hid)});\n")
                    body.append(f"    let {n} = crate::guard::ptr_or(&r{i}, {n});\n")
            elif act == "deny_addr":
                n = args[r["target_args"][0]][0]
                body.append(f"    if crate::guard::addr_denied({rs(hid)}, {n} as *const u8) {{\n")
                body.append(f"        crate::guard::set_last_error_{r['error_api']}({r['deny_error']});\n")
                body.append(f"        return {r['deny_ret']};\n    }}\n")
            elif act == "deny_name":
                n = args[r["target_args"][0]][0]
                body.append(f"    if crate::guard::name_denied_{r['name_kind']}({rs(hid)}, {n}) {{\n")
                body.append(f"        crate::guard::set_last_error_{r['error_api']}({r['deny_error']});\n")
                body.append(f"        return {r['deny_ret']};\n    }}\n")
            else:
                raise SystemExit(f"unknown action {act} in hooks.{hid}")
            o.append(f"pub unsafe extern \"system\" fn detour_{hid}({params}) -> {ret} {{\n")
            o.append(f"    let orig: {fn_ty} = core::mem::transmute(ORIG_{up}.load(Ordering::Relaxed));\n")
            o.extend(body)
            o.append(f"    orig({names})\n}}\n")
        # compile-time check: the detour has exactly the signature of the hooked function
        o.append(f"const _: {fn_ty} = detour_{hid};\n\n")
        specs.append(
            "        HookSpec { "
            f"id: {rs(hid)}, system: {rs(r['system'])}, module: {rs(r['module'])}, fallback_module: {rs('' if r['fallback_module'] == 'none' else r['fallback_module'])}, function: {rs(r['function'])}, "
            f"optional: {str(r['optional']).lower()}, detour: detour_{hid} as *const () as usize as *mut c_void, original: &ORIG_{up} }},\n"
        )
    o.append("pub fn hook_specs() -> Vec<HookSpec> {\n    vec![\n")
    o.extend(specs)
    o.append("    ]\n}\n")
    return "".join(o)


def outputs(ms):
    return {
        ROOT / "crates/common/src/generated/files.rs": gen_files(ms),
        ROOT / "crates/hook/src/generated.rs": gen_hooks(ms),
    }


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--milestone", type=int, default=1, help="generate rows up to this milestone (default 1)")
    args = ap.parse_args()
    stale = []
    for path, text in outputs(args.milestone).items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != text:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
            print(f"wrote {path.relative_to(ROOT)}")
    if stale:
        print("STALE generated files (run tools/gen.py):\n  " + "\n  ".join(stale))
        return 1
    if args.check:
        print("generated files are up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
