//! Files the launcher writes for the hook DLL and for ModEngine2.

use serde::{Deserialize, Serialize};
use std::fs;
use std::io;
use std::path::Path;

/// Optional in-game features. All off unless the launcher switches them on; an old config without this block
/// means "none".
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, Eq, Default)]
pub struct Features {
    /// A strictly read-only look at the running game (version, weapon table, inventory, text) written to
    /// `probe-ds3.txt` and `probe-ds3-weapons.csv` next to the hook log. Used by private test kits only.
    #[serde(default)]
    pub probe: bool,
    /// Space Marine 2 sounds for swings and shots (needs the WAV files the setup tool prepared in `assets_dir`).
    #[serde(default)]
    pub sounds: bool,
    /// Private test kits only: hotkey experiments that CHANGE the running game (F8: put the test weapons in the
    /// inventory). Everything else is read-only or plays sound.
    #[serde(default)]
    pub experiments: bool,
    /// Private test kits only: write the new names of the test weapons over the old ones in the running game's memory
    /// (`logs/rename.txt`). Needs no archive; changes only the text of those names, in place.
    #[serde(default)]
    pub rename: bool,
}

/// What the hook DLL needs to know. Written by the launcher before every launch (sheet: files.hook_config).
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct HookConfig {
    pub version: String,
    /// The game's real save folder, e.g. `C:\Users\you\AppData\Roaming\DarkSoulsIII`.
    pub real_save_dir: String,
    /// The mashup's private copy that file access is redirected to.
    pub sandbox_save_dir: String,
    pub log_file: String,
    /// Appended to the game window title.
    pub window_suffix: String,
    /// No message boxes (automated tests).
    pub silent: bool,
    /// Always true in a release. Tests switch it off for a control run that proves the guard does something.
    pub block_network: bool,
    #[serde(default)]
    pub features: Features,
    /// Folder holding what the setup tool prepared (`sounds/index.json` and the WAV files). Empty = none.
    #[serde(default)]
    pub assets_dir: String,
}

impl HookConfig {
    pub fn load(path: &Path) -> io::Result<Self> {
        let text = fs::read_to_string(path)?;
        serde_json::from_str(&text).map_err(|e| io::Error::new(io::ErrorKind::InvalidData, e))
    }

    pub fn save(&self, path: &Path) -> io::Result<()> {
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)?;
        }
        let text = serde_json::to_string_pretty(self).map_err(|e| io::Error::new(io::ErrorKind::InvalidData, e))?;
        fs::write(path, text)
    }
}

fn toml_path(p: &Path) -> String {
    p.to_string_lossy().replace('\\', "/").replace('"', "\\\"")
}

/// ModEngine2 config (sheet: files.me2_config): loads the hook DLL and the mod folder. The rest mirrors
/// ModEngine2's own `config_darksouls3.toml` defaults.
pub fn me2_toml(hook_dll: &Path, mod_dir: &Path) -> String {
    format!(
        "# Generated by Ashen Marine before every launch. Do not edit.\n\
[modengine]\n\
debug = false\n\
external_dlls = [\"{dll}\"]\n\
\n\
[extension.mod_loader]\n\
enabled = true\n\
loose_params = false\n\
mods = [\n    {{ enabled = true, name = \"ashenmarine\", path = \"{mods}\" }}\n]\n\
\n\
[extension.scylla_hide]\n\
enabled = true\n",
        dll = toml_path(hook_dll),
        mods = toml_path(mod_dir)
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn toml_uses_forward_slashes_and_the_right_keys() {
        let t = me2_toml(Path::new(r"C:\Melty\managed\ashenmarine\ashenmarine_hook.dll"), Path::new(r"C:\Melty\managed\ashenmarine\mod"));
        assert!(t.contains(r#"external_dlls = ["C:/Melty/managed/ashenmarine/ashenmarine_hook.dll"]"#), "{t}");
        assert!(t.contains(r#"path = "C:/Melty/managed/ashenmarine/mod""#));
        assert!(t.contains("[extension.mod_loader]") && t.contains("[extension.scylla_hide]"));
        assert!(!t.contains('\\'), "no backslashes: they are escapes in TOML");
    }

    #[test]
    fn config_roundtrip() {
        let dir = tempfile::tempdir().unwrap();
        let c = HookConfig {
            version: "0.1.0".into(),
            real_save_dir: r"C:\a\DarkSoulsIII".into(),
            sandbox_save_dir: r"D:\b\DarkSoulsIII".into(),
            log_file: r"D:\b\hook.log".into(),
            window_suffix: " - x".into(),
            silent: true,
            block_network: true,
            features: Features { probe: true, sounds: true, experiments: true, rename: true },
            assets_dir: r"D:\b\assets".into(),
        };
        let p = dir.path().join("sub/ashenmarine.json");
        c.save(&p).unwrap();
        assert_eq!(HookConfig::load(&p).unwrap(), c);
    }

    #[test]
    fn an_old_config_without_features_means_none() {
        let old = r#"{"version":"0.1.0","real_save_dir":"a","sandbox_save_dir":"b","log_file":"c","window_suffix":"","silent":false,"block_network":true}"#;
        let dir = tempfile::tempdir().unwrap();
        let p = dir.path().join("c.json");
        std::fs::write(&p, old).unwrap();
        let c = HookConfig::load(&p).unwrap();
        assert_eq!(c.features, Features::default());
        assert_eq!(c.assets_dir, "");
    }
}
